### ISSUE TITLE
Use VS Code clipboard API (for remote support)

### ISSUE THREAD

**Issue by YayC** [mpcarolin/vscode-line-linker#2]
Please see https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard

**Comment by YayC** [comment]
Actually not sure if you can open a remote file via link. It would take more than this anyway. You may still want to use the API, but closing for my remote use-case

**Comment by mpcarolin** [comment]
Interesting, I'll have to look into this part of the API. Can you tell me more about your use case? Are you referring to opening remote files in vscode remote explorer?

**Comment by YayC** [comment]
Hey Michael, thanks for your reply. Yea I mostly edit files on a remote server via the [Remote-SSH extension](https://code.visualstudio.com/docs/remote/ssh). I doubt there's a way to specify the host in a file link so vscode knows to open the file in the remote workspace rather than local disk.
